/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface HabitTreeInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "achievementCount"
      | "achievements"
      | "archiveHabit"
      | "authorizeAllDailyRecords"
      | "authorizeDailyRecords"
      | "checkAchievementEncrypted"
      | "checkFixedAchievementEncrypted"
      | "confidentialProtocolId"
      | "createAchievement"
      | "createCustomBadge"
      | "createHabit"
      | "customBadgeCount"
      | "customBadges"
      | "dailyRecords"
      | "deleteHabit"
      | "fixedAchievementMinted"
      | "fixedAchievementUnlocked"
      | "fixedAchievementUnlockedAt"
      | "getAchievement"
      | "getAchievementCount"
      | "getCustomBadge"
      | "getCustomBadgeCount"
      | "getDailyRecord"
      | "getFixedAchievementCount"
      | "getFixedAchievementMeta"
      | "getFixedAchievementStatus"
      | "getHabit"
      | "getHabitGrowth"
      | "getRecordCount"
      | "getStreakDays"
      | "getTotalProgress"
      | "habitCount"
      | "habitGrowth"
      | "habits"
      | "mintCustomBadge"
      | "mintFixedAchievementBadge"
      | "recordCount"
      | "streakDays"
      | "submitProgress"
      | "totalProgress"
      | "unlockAchievement"
      | "unlockCustomBadge"
      | "unlockFixedAchievement"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AchievementUnlocked"
      | "CustomBadgeCreated"
      | "CustomBadgeMinted"
      | "CustomBadgeUnlocked"
      | "FixedAchievementMinted"
      | "FixedAchievementUnlocked"
      | "HabitArchived"
      | "HabitCreated"
      | "HabitDeleted"
      | "ProgressSubmitted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "achievementCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "achievements",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "archiveHabit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeAllDailyRecords",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "authorizeDailyRecords",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkAchievementEncrypted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "checkFixedAchievementEncrypted",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "confidentialProtocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "createAchievement",
    values: [BigNumberish, string, string, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createCustomBadge",
    values: [
      BigNumberish,
      string,
      string,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "createHabit",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "customBadgeCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "customBadges",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "dailyRecords",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteHabit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fixedAchievementMinted",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fixedAchievementUnlocked",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fixedAchievementUnlockedAt",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getAchievementCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCustomBadge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getCustomBadgeCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDailyRecord",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedAchievementCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedAchievementMeta",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFixedAchievementStatus",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHabit",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHabitGrowth",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getRecordCount",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getStreakDays",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalProgress",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "habitCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "habitGrowth",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "habits",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintCustomBadge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "mintFixedAchievementBadge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "recordCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "streakDays",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "submitProgress",
    values: [BigNumberish, BytesLike, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "totalProgress",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockAchievement",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockCustomBadge",
    values: [BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unlockFixedAchievement",
    values: [BigNumberish, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "achievementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "achievements",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "archiveHabit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeAllDailyRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "authorizeDailyRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkAchievementEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "checkFixedAchievementEncrypted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "confidentialProtocolId",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createCustomBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createHabit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "customBadgeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "customBadges",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "dailyRecords",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteHabit",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fixedAchievementMinted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fixedAchievementUnlocked",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fixedAchievementUnlockedAt",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getAchievementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCustomBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCustomBadgeCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDailyRecord",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedAchievementCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedAchievementMeta",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFixedAchievementStatus",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHabit", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getHabitGrowth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRecordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStreakDays",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "habitCount", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "habitGrowth",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "habits", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "mintCustomBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "mintFixedAchievementBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "recordCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "streakDays", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "totalProgress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockAchievement",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockCustomBadge",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unlockFixedAchievement",
    data: BytesLike
  ): Result;
}

export namespace AchievementUnlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    achievementId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    habitId: bigint,
    achievementId: bigint
  ];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    achievementId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustomBadgeCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    badgeId: BigNumberish
  ];
  export type OutputTuple = [user: string, habitId: bigint, badgeId: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    badgeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustomBadgeMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    badgeId: BigNumberish
  ];
  export type OutputTuple = [user: string, habitId: bigint, badgeId: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    badgeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CustomBadgeUnlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    badgeId: BigNumberish
  ];
  export type OutputTuple = [user: string, habitId: bigint, badgeId: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    badgeId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FixedAchievementMintedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    achievementId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    habitId: bigint,
    achievementId: bigint
  ];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    achievementId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace FixedAchievementUnlockedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    achievementId: BigNumberish
  ];
  export type OutputTuple = [
    user: string,
    habitId: bigint,
    achievementId: bigint
  ];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    achievementId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HabitArchivedEvent {
  export type InputTuple = [user: AddressLike, habitId: BigNumberish];
  export type OutputTuple = [user: string, habitId: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HabitCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    name: string,
    category: string
  ];
  export type OutputTuple = [
    user: string,
    habitId: bigint,
    name: string,
    category: string
  ];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    name: string;
    category: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace HabitDeletedEvent {
  export type InputTuple = [user: AddressLike, habitId: BigNumberish];
  export type OutputTuple = [user: string, habitId: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ProgressSubmittedEvent {
  export type InputTuple = [
    user: AddressLike,
    habitId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, habitId: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    habitId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface HabitTree extends BaseContract {
  connect(runner?: ContractRunner | null): HabitTree;
  waitForDeployment(): Promise<this>;

  interface: HabitTreeInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  achievementCount: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  achievements: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        description: string;
        threshold: string;
        isUnlocked: boolean;
        unlockedAt: bigint;
      }
    ],
    "view"
  >;

  archiveHabit: TypedContractMethod<
    [habitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizeAllDailyRecords: TypedContractMethod<
    [habitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  authorizeDailyRecords: TypedContractMethod<
    [habitId: BigNumberish, fromIndex: BigNumberish, toIndex: BigNumberish],
    [void],
    "nonpayable"
  >;

  checkAchievementEncrypted: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [string],
    "nonpayable"
  >;

  checkFixedAchievementEncrypted: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [string],
    "nonpayable"
  >;

  confidentialProtocolId: TypedContractMethod<[], [bigint], "view">;

  createAchievement: TypedContractMethod<
    [
      habitId: BigNumberish,
      name: string,
      description: string,
      thresholdEuint32: BytesLike,
      thresholdProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;

  createCustomBadge: TypedContractMethod<
    [
      habitId: BigNumberish,
      name: string,
      description: string,
      metric: BigNumberish,
      operatorCode: BigNumberish,
      threshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  createHabit: TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;

  customBadgeCount: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  customBadges: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        metric: bigint;
        operatorCode: bigint;
        threshold: bigint;
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;

  dailyRecords: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, string] & { timestamp: bigint; progress: string }],
    "view"
  >;

  deleteHabit: TypedContractMethod<
    [habitId: BigNumberish],
    [void],
    "nonpayable"
  >;

  fixedAchievementMinted: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  fixedAchievementUnlocked: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [boolean],
    "view"
  >;

  fixedAchievementUnlockedAt: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;

  getAchievement: TypedContractMethod<
    [habitId: BigNumberish, index: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        description: string;
        threshold: string;
        isUnlocked: boolean;
        unlockedAt: bigint;
      }
    ],
    "view"
  >;

  getAchievementCount: TypedContractMethod<
    [habitId: BigNumberish],
    [bigint],
    "view"
  >;

  getCustomBadge: TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        metric: bigint;
        operatorCode: bigint;
        threshold: bigint;
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;

  getCustomBadgeCount: TypedContractMethod<
    [habitId: BigNumberish],
    [bigint],
    "view"
  >;

  getDailyRecord: TypedContractMethod<
    [habitId: BigNumberish, recordIndex: BigNumberish],
    [[bigint, string] & { timestamp: bigint; progress: string }],
    "view"
  >;

  getFixedAchievementCount: TypedContractMethod<[], [bigint], "view">;

  getFixedAchievementMeta: TypedContractMethod<
    [achievementId: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        name: string;
        description: string;
        metric: bigint;
        threshold: bigint;
      }
    ],
    "view"
  >;

  getFixedAchievementStatus: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [
      [boolean, bigint, boolean] & {
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;

  getHabit: TypedContractMethod<
    [habitId: BigNumberish],
    [
      [bigint, string, string, boolean, boolean, bigint] & {
        id: bigint;
        name: string;
        category: string;
        isActive: boolean;
        isArchived: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  getHabitGrowth: TypedContractMethod<
    [habitId: BigNumberish],
    [string],
    "view"
  >;

  getRecordCount: TypedContractMethod<
    [habitId: BigNumberish],
    [bigint],
    "view"
  >;

  getStreakDays: TypedContractMethod<[habitId: BigNumberish], [string], "view">;

  getTotalProgress: TypedContractMethod<
    [habitId: BigNumberish],
    [string],
    "view"
  >;

  habitCount: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  habitGrowth: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  habits: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string, boolean, boolean, bigint] & {
        id: bigint;
        name: string;
        category: string;
        isActive: boolean;
        isArchived: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;

  mintCustomBadge: TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  mintFixedAchievementBadge: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  recordCount: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;

  streakDays: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  submitProgress: TypedContractMethod<
    [habitId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;

  totalProgress: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;

  unlockAchievement: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockCustomBadge: TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [void],
    "nonpayable"
  >;

  unlockFixedAchievement: TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "achievementCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "achievements"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        description: string;
        threshold: string;
        isUnlocked: boolean;
        unlockedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "archiveHabit"
  ): TypedContractMethod<[habitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeAllDailyRecords"
  ): TypedContractMethod<[habitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "authorizeDailyRecords"
  ): TypedContractMethod<
    [habitId: BigNumberish, fromIndex: BigNumberish, toIndex: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkAchievementEncrypted"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "checkFixedAchievementEncrypted"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "confidentialProtocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "createAchievement"
  ): TypedContractMethod<
    [
      habitId: BigNumberish,
      name: string,
      description: string,
      thresholdEuint32: BytesLike,
      thresholdProof: BytesLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createCustomBadge"
  ): TypedContractMethod<
    [
      habitId: BigNumberish,
      name: string,
      description: string,
      metric: BigNumberish,
      operatorCode: BigNumberish,
      threshold: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createHabit"
  ): TypedContractMethod<
    [name: string, category: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "customBadgeCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "customBadges"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        metric: bigint;
        operatorCode: bigint;
        threshold: bigint;
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "dailyRecords"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [[bigint, string] & { timestamp: bigint; progress: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "deleteHabit"
  ): TypedContractMethod<[habitId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fixedAchievementMinted"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "fixedAchievementUnlocked"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "fixedAchievementUnlockedAt"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish, arg2: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAchievement"
  ): TypedContractMethod<
    [habitId: BigNumberish, index: BigNumberish],
    [
      [bigint, string, string, string, boolean, bigint] & {
        id: bigint;
        name: string;
        description: string;
        threshold: string;
        isUnlocked: boolean;
        unlockedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getAchievementCount"
  ): TypedContractMethod<[habitId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getCustomBadge"
  ): TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [
      [
        bigint,
        string,
        string,
        bigint,
        bigint,
        bigint,
        boolean,
        bigint,
        boolean
      ] & {
        id: bigint;
        name: string;
        description: string;
        metric: bigint;
        operatorCode: bigint;
        threshold: bigint;
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCustomBadgeCount"
  ): TypedContractMethod<[habitId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDailyRecord"
  ): TypedContractMethod<
    [habitId: BigNumberish, recordIndex: BigNumberish],
    [[bigint, string] & { timestamp: bigint; progress: string }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFixedAchievementCount"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getFixedAchievementMeta"
  ): TypedContractMethod<
    [achievementId: BigNumberish],
    [
      [string, string, bigint, bigint] & {
        name: string;
        description: string;
        metric: bigint;
        threshold: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getFixedAchievementStatus"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [
      [boolean, bigint, boolean] & {
        isUnlocked: boolean;
        unlockedAt: bigint;
        isMinted: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHabit"
  ): TypedContractMethod<
    [habitId: BigNumberish],
    [
      [bigint, string, string, boolean, boolean, bigint] & {
        id: bigint;
        name: string;
        category: string;
        isActive: boolean;
        isArchived: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getHabitGrowth"
  ): TypedContractMethod<[habitId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getRecordCount"
  ): TypedContractMethod<[habitId: BigNumberish], [bigint], "view">;
  getFunction(
    nameOrSignature: "getStreakDays"
  ): TypedContractMethod<[habitId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getTotalProgress"
  ): TypedContractMethod<[habitId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "habitCount"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "habitGrowth"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "habits"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [
      [bigint, string, string, boolean, boolean, bigint] & {
        id: bigint;
        name: string;
        category: string;
        isActive: boolean;
        isArchived: boolean;
        createdAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "mintCustomBadge"
  ): TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintFixedAchievementBadge"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "recordCount"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "streakDays"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "submitProgress"
  ): TypedContractMethod<
    [habitId: BigNumberish, inputEuint32: BytesLike, inputProof: BytesLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "totalProgress"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "unlockAchievement"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockCustomBadge"
  ): TypedContractMethod<
    [habitId: BigNumberish, badgeId: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unlockFixedAchievement"
  ): TypedContractMethod<
    [habitId: BigNumberish, achievementId: BigNumberish],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AchievementUnlocked"
  ): TypedContractEvent<
    AchievementUnlockedEvent.InputTuple,
    AchievementUnlockedEvent.OutputTuple,
    AchievementUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "CustomBadgeCreated"
  ): TypedContractEvent<
    CustomBadgeCreatedEvent.InputTuple,
    CustomBadgeCreatedEvent.OutputTuple,
    CustomBadgeCreatedEvent.OutputObject
  >;
  getEvent(
    key: "CustomBadgeMinted"
  ): TypedContractEvent<
    CustomBadgeMintedEvent.InputTuple,
    CustomBadgeMintedEvent.OutputTuple,
    CustomBadgeMintedEvent.OutputObject
  >;
  getEvent(
    key: "CustomBadgeUnlocked"
  ): TypedContractEvent<
    CustomBadgeUnlockedEvent.InputTuple,
    CustomBadgeUnlockedEvent.OutputTuple,
    CustomBadgeUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "FixedAchievementMinted"
  ): TypedContractEvent<
    FixedAchievementMintedEvent.InputTuple,
    FixedAchievementMintedEvent.OutputTuple,
    FixedAchievementMintedEvent.OutputObject
  >;
  getEvent(
    key: "FixedAchievementUnlocked"
  ): TypedContractEvent<
    FixedAchievementUnlockedEvent.InputTuple,
    FixedAchievementUnlockedEvent.OutputTuple,
    FixedAchievementUnlockedEvent.OutputObject
  >;
  getEvent(
    key: "HabitArchived"
  ): TypedContractEvent<
    HabitArchivedEvent.InputTuple,
    HabitArchivedEvent.OutputTuple,
    HabitArchivedEvent.OutputObject
  >;
  getEvent(
    key: "HabitCreated"
  ): TypedContractEvent<
    HabitCreatedEvent.InputTuple,
    HabitCreatedEvent.OutputTuple,
    HabitCreatedEvent.OutputObject
  >;
  getEvent(
    key: "HabitDeleted"
  ): TypedContractEvent<
    HabitDeletedEvent.InputTuple,
    HabitDeletedEvent.OutputTuple,
    HabitDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ProgressSubmitted"
  ): TypedContractEvent<
    ProgressSubmittedEvent.InputTuple,
    ProgressSubmittedEvent.OutputTuple,
    ProgressSubmittedEvent.OutputObject
  >;

  filters: {
    "AchievementUnlocked(address,uint256,uint256)": TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;
    AchievementUnlocked: TypedContractEvent<
      AchievementUnlockedEvent.InputTuple,
      AchievementUnlockedEvent.OutputTuple,
      AchievementUnlockedEvent.OutputObject
    >;

    "CustomBadgeCreated(address,uint256,uint256)": TypedContractEvent<
      CustomBadgeCreatedEvent.InputTuple,
      CustomBadgeCreatedEvent.OutputTuple,
      CustomBadgeCreatedEvent.OutputObject
    >;
    CustomBadgeCreated: TypedContractEvent<
      CustomBadgeCreatedEvent.InputTuple,
      CustomBadgeCreatedEvent.OutputTuple,
      CustomBadgeCreatedEvent.OutputObject
    >;

    "CustomBadgeMinted(address,uint256,uint256)": TypedContractEvent<
      CustomBadgeMintedEvent.InputTuple,
      CustomBadgeMintedEvent.OutputTuple,
      CustomBadgeMintedEvent.OutputObject
    >;
    CustomBadgeMinted: TypedContractEvent<
      CustomBadgeMintedEvent.InputTuple,
      CustomBadgeMintedEvent.OutputTuple,
      CustomBadgeMintedEvent.OutputObject
    >;

    "CustomBadgeUnlocked(address,uint256,uint256)": TypedContractEvent<
      CustomBadgeUnlockedEvent.InputTuple,
      CustomBadgeUnlockedEvent.OutputTuple,
      CustomBadgeUnlockedEvent.OutputObject
    >;
    CustomBadgeUnlocked: TypedContractEvent<
      CustomBadgeUnlockedEvent.InputTuple,
      CustomBadgeUnlockedEvent.OutputTuple,
      CustomBadgeUnlockedEvent.OutputObject
    >;

    "FixedAchievementMinted(address,uint256,uint8)": TypedContractEvent<
      FixedAchievementMintedEvent.InputTuple,
      FixedAchievementMintedEvent.OutputTuple,
      FixedAchievementMintedEvent.OutputObject
    >;
    FixedAchievementMinted: TypedContractEvent<
      FixedAchievementMintedEvent.InputTuple,
      FixedAchievementMintedEvent.OutputTuple,
      FixedAchievementMintedEvent.OutputObject
    >;

    "FixedAchievementUnlocked(address,uint256,uint8)": TypedContractEvent<
      FixedAchievementUnlockedEvent.InputTuple,
      FixedAchievementUnlockedEvent.OutputTuple,
      FixedAchievementUnlockedEvent.OutputObject
    >;
    FixedAchievementUnlocked: TypedContractEvent<
      FixedAchievementUnlockedEvent.InputTuple,
      FixedAchievementUnlockedEvent.OutputTuple,
      FixedAchievementUnlockedEvent.OutputObject
    >;

    "HabitArchived(address,uint256)": TypedContractEvent<
      HabitArchivedEvent.InputTuple,
      HabitArchivedEvent.OutputTuple,
      HabitArchivedEvent.OutputObject
    >;
    HabitArchived: TypedContractEvent<
      HabitArchivedEvent.InputTuple,
      HabitArchivedEvent.OutputTuple,
      HabitArchivedEvent.OutputObject
    >;

    "HabitCreated(address,uint256,string,string)": TypedContractEvent<
      HabitCreatedEvent.InputTuple,
      HabitCreatedEvent.OutputTuple,
      HabitCreatedEvent.OutputObject
    >;
    HabitCreated: TypedContractEvent<
      HabitCreatedEvent.InputTuple,
      HabitCreatedEvent.OutputTuple,
      HabitCreatedEvent.OutputObject
    >;

    "HabitDeleted(address,uint256)": TypedContractEvent<
      HabitDeletedEvent.InputTuple,
      HabitDeletedEvent.OutputTuple,
      HabitDeletedEvent.OutputObject
    >;
    HabitDeleted: TypedContractEvent<
      HabitDeletedEvent.InputTuple,
      HabitDeletedEvent.OutputTuple,
      HabitDeletedEvent.OutputObject
    >;

    "ProgressSubmitted(address,uint256,uint256)": TypedContractEvent<
      ProgressSubmittedEvent.InputTuple,
      ProgressSubmittedEvent.OutputTuple,
      ProgressSubmittedEvent.OutputObject
    >;
    ProgressSubmitted: TypedContractEvent<
      ProgressSubmittedEvent.InputTuple,
      ProgressSubmittedEvent.OutputTuple,
      ProgressSubmittedEvent.OutputObject
    >;
  };
}
